### ISSUE TITLE
Incorrect titles - they need to be swapped 

### ISSUE THREAD

**Issue by fafk** [RavenProject/ravenproject.github.io#108]
![Screenshot 2020-01-22 at 11 17 37](https://user-images.githubusercontent.com/4518474/72886008-4cc1f100-3d09-11ea-9c6f-50c77160bad5.png)
![Screenshot 2020-01-22 at 11 17 03](https://user-images.githubusercontent.com/4518474/72886009-4cc1f100-3d09-11ea-8d02-da0dcdaf8d26.png)

**Comment by fafk** [comment]
Tab PROJECT SHARES should have a subtitle "Representing a share of a project".

Tab PHYSICAL & DIGITAL ASSETS should have a subtitle "Representing real world custodied physical or digital asset"

**Comment by jeroz1** [comment]
Thanks for the report!
