### ISSUE TITLE
Listing on ravencoin.org

### ISSUE THREAD

**Issue by AntonySS-manager** [RavenProject/ravenproject.github.io#123]
Hey! I'm Antony from SwapSpace project. I would like to list our excgange on your website. Could you help me out please

**Comment by TronBlack** [comment]
Absolutely.

Just clone this repo, edit:
https://github.com/RavenProject/ravenproject.github.io/blob/master/_data/exchanges.yml

And do a pull request back to master.

Be fair and don't add your exchange to the top or make an outlandish jpg or it might get flagged as being greedy.

Somebody will review it and approve the PR, and your exchange will show up on the website.

Cheers,
Tron

**Comment by AntonySS-manager** [comment]
Thank you for your explanation!

All the best,
Antony

**Comment by jeroz1** [comment]
Addressed in #124
