### ISSUE TITLE
Broken discord link on the ravencoin.org website

### ISSUE THREAD

**Issue by belgracing** [RavenProject/ravenproject.github.io#138]
This link doesn't work.

![image](https://user-images.githubusercontent.com/30867950/81080330-4b53b780-8ef9-11ea-9fa7-c994479d2858.png)

**Comment by jeroz1** [comment]
The link works for me and I don't see any recent changes that addressed it between now and when you opened the request.

**Comment by thatsmybirthday** [comment]
The link works. This issue should be closed.
