### ISSUE TITLE
Add D'CENT wallet in 3rd party wallet list

### ISSUE THREAD

**Issue by paromix** [RavenProject/ravenproject.github.io#147]
Hi Ravencoin team!
I would like to add D'CENT wallet into 3rd party wallet list. (https://ravencoin.org/wallet/)
D'CENT wallet supports Ravencoin from March. You can see at https://dcentwallet.com/products/BiometricWallet

I provide the information of D'CENT wallet below. If some more actions are required, please let me know about that. Of course, I can create PR for it.

### D'CENT wallet information

Here is the related information
* Android / iOS support
* Website : https://dcentwallet.com/
* Logo
![dcent_logo_2](https://user-images.githubusercontent.com/20573044/84689162-84ad2780-af7b-11ea-8ff0-bf2ccfdad50a.png)

**Comment by jeroz1** [comment]
Addressed in #148
