### ISSUE TITLE
About your token

### ISSUE THREAD

**Issue by Popa24** [RavenProject/ravenproject.github.io#157]
Hi, we recently started evorese.com, an exchange in partnership with Birake. As we have your coin listed on our exchange, it would be great if you could also list us on your website. Many thanks.
Also, this is the link: https://evorese.com/
And this is our logo: 
![WhatsApp Image 2020-07-31 at 13 47 45](https://user-images.githubusercontent.com/62101412/89883428-d3b8b700-dbd0-11ea-99a2-612af03a3a4d.jpeg)

**Comment by jeroz1** [comment]
addressed in #164
