### ISSUE TITLE
Website bug! 

### ISSUE THREAD

**Issue by Raco0on** [RavenProject/ravenproject.github.io#16]
Hi devs! 

I found one little issue on Ravencoin.com mobile version side... The issue is that, after click, drop-down menu appears behind the banner... I think that's overflow problem.... So the mission is very simple but very boring for users who visit the site... 

**RKmfWtWb1AWmxozy6fR9SEa89NJayCGFBW** - Here is my Ravencoin wallet address, so you can give me some airdrops for reporting this issue, Or you can do not... )))) Anyway I am hoping in this project and believe in the success of your group!  

With RVN-Love !  🥇 👍

**Comment by fokep** [comment]
I'm unable to replicate this bug. Can try some different phones later but it would be helpful it you could tell what device you are using? (And which browser)

**Comment by Raco0on** [comment]
I am using LG V10 but you also can see it in the browse. Chrome for example... Go to inspect page, than change resolution to make menu change to drop down... Then open the drop down menu and klick for example about link... After you jump on the about page try drop down the menu.. After you will see that issue.. The menu goes behind the banner... :)
P.S. the menu works only on home page

**Comment by Raco0on** [comment]
It is working now :)

**Comment by fokep** [comment]
Fantastic! **RX17aUYaMCLt4FTw4ygy9fmSFWu8zL3BpZ** if you want to buy me a beer 😂

**Comment by Raco0on** [comment]
Hahaaa, are you kidding? I found that bug and reported, I deserve some beer from dev team! )))))

**Comment by Raco0on** [comment]
Ahahaha, that's nice move from your side. That means, that you appreciate your community ppl...  Thanx... And wish you more successes and pumps... 😄😄  By the way i have 100x100 and i am still mining ant buying on drops)))) go rvn go!

**Comment by mcshinskyredlist** [comment]
Thanks for the fix!

**Comment by mmcshinsky** [comment]
Thanks for the fix!

**Comment by TronBlack** [comment]
Thank you Raco0on
