### ISSUE TITLE
Offline exchange in your overview

### ISSUE THREAD

**Issue by greenbroccoli** [RavenProject/ravenproject.github.io#160]
Hello Ravencoin Team,

Hope you're all healthy :). I was just visiting https://ravencoin.org/ and saw that the Bitqist exchange is still listed on your website. Unfortunately they closed down due to stricter regulations in The Netherlands. The URL is also going to a blank page. Should be better to remove that.

On top of that, the Digfinex URL should be updated to https://www.digifinex.com/en-ww/trade/BTC/RVN (the current link is giving a 403 error).

Lastly, I was hoping that you could maybe feature my website https://cryptotips.eu/en/buy/buy-ravencoin/ on https://ravencoin.org/community/ (preferably dofollow, just as all the other links on that page). That would really help me.

Have a great weekend and you can contact me if you have any questions.

**Comment by jeroz1** [comment]
Thank you very much for pointing out these errors. 

Unfortunately, I am not sure how your website would fit in the Ravencoin community page. This page links to community resources that are primarily aimed at Ravencoin while your page offers a middle man / referral service between traders and exchanges for various crypto projects.

**Comment by jeroz1** [comment]
Site issues addressed in #164
