### ISSUE TITLE
Exolix Exchange - please, add to the list

### ISSUE THREAD

**Issue by Exolix-com** [RavenProject/ravenproject.github.io#161]
Dear RavenCoin Team,

We are Exolix, a secure and anonymous crypto exchange service with fixed rates. We have RVN listed on Exolix for exchange.
We noticed that your website lists exchanges that support RVN trading and we would like to ask to be included within this list. We have discussed this with an Admin from the Ravencoin telegram group who directed us here and said to provide our logo (see attached) and RVN markets URL. It would be great to be featured as a Non-Custodial exchange.
https://exolix.com/exchange/BTC-RVN
https://exolix.com/exchange/RVN-BTC

We are looking forward to the mutual cooperation.

If you have any questions please do not hesitate to contact us.

Best Regards,
Exolix Team
https://exolix.com/
![logo_exolix](https://user-images.githubusercontent.com/56387346/93074731-74493d80-f68d-11ea-9ed0-2ede6749c225.png)

**Comment by jeroz1** [comment]
addressed in #164
