### ISSUE TITLE
Free Partnership 

### ISSUE THREAD

**Issue by IanaGatsby** [RavenProject/ravenproject.github.io#162]
My name is Iana, I’m Head of Marketing at Revain project. 
Revain is the blockchain-based review platform for crypto community. Since launch, we became the biggest source of authentic user reviews on thousands of crypto projects, exchanges, wallets and more. We have an active and passionate base of people interested in exploring crypto market and providing their feedback on various companies and tokens. 
I'm happy to tell you that RavenCoin is listed on Revain. Here is the page: https://revain.org/projects/ravencoin
Revain Widget is a simple and safe tool which will allow you to put reviews on RavenCoin from Revain into your website. After that, the visitors of your website will be able to see reviews on you, as well as write ones without leaving the website. High-quality feedback is always great for trust building among your community. Here are examples of some projects that already installed Revain Widget (scroll down to the bottom of the websites): Zilliqa: https://www.zilliqa.com/Fusion: https://www.fusion.org/developers/overviewEmirex exchange https://emirex.comDragonEx exchange https://dragonex.io/en-us/Vitae Token https://www.vitaetoken.ioBitcoinox https://bitcoinox.com
Revain Widget is completely free and effortless to install. You just need to customize your own Widget here and put a few lines of simple code into your website. It takes like 5 minutes.
Besides the Widget, we are going to promote your project on our channels (Twitter, Telegram, Bitcointalk, Facebook, email, etc.) and launch a review competition. Participants will have to write high-quality reviews on your project and authors will receive token rewards from Revain. All this will bring more attention to your project, both from your audience and ours. 
Let me know if you are interested.
https://revain.org/public-api/widgets/create
Here is the widget

**Comment by TronBlack** [comment]
Thank you.  I'll take a look at it.

**Comment by jeroz1** [comment]
Addressed in #163
