### ISSUE TITLE
New Raven Mining Pool Addition to https://ravencoin.org/pools/

### ISSUE THREAD

**Issue by forallchaitu83** [RavenProject/ravenproject.github.io#166]
Hi Team,

We would like to have our New Raven Mining Pool listed on your page - https://ravencoin.org/pools/

Our Pool - https://rvn.bsmith.io

Request you to kindly do the needful.

Best Regards,
Chaitanya

**Comment by Synicide** [comment]
Created pull request: https://github.com/RavenProject/ravenproject.github.io/pull/167
It can be previewed at: https://synicide.github.io/pools/

**Comment by jeroz1** [comment]
addressed in #167
