### ISSUE TITLE
Translation in German

### ISSUE THREAD

**Issue by Musicals001** [RavenProject/ravenproject.github.io#23]
I have the x-16, Roadmap and the Ravencoin Info translating to german.

[X16R-Whitepaper translated.docx](https://github.com/RavenProject/ravenproject.github.io/files/2523306/X16R-Whitepaper.translated.docx)

[Ravencoin translated.docx](https://github.com/RavenProject/ravenproject.github.io/files/2523307/Ravencoin.translated.docx)

[Roadmap translated.docx](https://github.com/RavenProject/ravenproject.github.io/files/2523308/Roadmap.translated.docx)

**Comment by fokep** [comment]
Could you provide the translation in an alternative format? I don't think a lot of people would download docx files from unknown people, let alone open them in Word.

**Comment by fokep** [comment]
Alright. Here are pdf's. Might be nice to get a secondary to proofread before eventually including to web. I think we should have multiple translations made available on ravencoin.com and support your initiative @Musicals001 

[Ravencoin.translated.docx.pdf](https://github.com/RavenProject/ravenproject.github.io/files/2572637/Ravencoin.translated.docx.pdf)
[Roadmap.translated.docx.pdf](https://github.com/RavenProject/ravenproject.github.io/files/2572638/Roadmap.translated.docx.pdf)
[X16R-Whitepaper.translated.docx.pdf](https://github.com/RavenProject/ravenproject.github.io/files/2572639/X16R-Whitepaper.translated.docx.pdf)

**Comment by blondfrogs** [comment]
We are getting these documents verified by another german speaker. Once verified, we will find a good place to put them on the website. 

Thanks.

**Comment by spyder46n2** [comment]
Almost ready to publish. Just need to finalize a few odds and ends.  Should look something like this:
![image](https://user-images.githubusercontent.com/33036650/54725249-007bb280-4b34-11e9-9c03-32afdf6b5d0d.png)

**Comment by spyder46n2** [comment]
This has been added to the site. Closing...
