### ISSUE TITLE
Please add Indodax Logo in exchange list

### ISSUE THREAD

**Issue by xzecode** [RavenProject/ravenproject.github.io#50]
![logo-indodax](https://user-images.githubusercontent.com/13211518/57278076-ce1c1980-70cf-11e9-855a-4a615fa729a0.png)

**Comment by jeroz1** [comment]
Thanks, I'll update the exchange list later this week. I see that it is severely outdated and also shows exchanges that closed down.

Source file is here: https://github.com/RavenProject/ravenproject.github.io/blob/master/_data/exchanges.yml

**Comment by blondfrogs** [comment]
I am unable to find a Ravencoin Pairing on the Indodax exchange.

**Comment by jeroz1** [comment]
Later today: https://blog.indodax.com/ravencoin-listing-on-indodax/

**Comment by blondfrogs** [comment]
Added in #51
