### ISSUE TITLE
Ravencoin Written Tutorial for Ledger Nano S and Electrum-Rvn Client

### ISSUE THREAD

**Issue by Zizaerion** [RavenProject/ravenproject.github.io#53]
**How to use the Ledger Nano S and Ledger Nano X with Ravencoin**

The Ledger Nano S and Ledger Nano X are hardware wallets.  Hardware wallets are the most secure method of storing the private keys used to spend your coins.  Installing the Ravencoin app will allow you to manage your Ravencoin.  It does not currently support managing Ravencoin Assets at this time.  When that function is available this document will be expanded to include instructions on how to manage Ravencoin assets.

**Before you begin**

-  Make sure that you have initialized your Ledger device
-  The latest firmware is installed
-  Ledger Live is ready to use
-  The bitcoin app is installed on your device

**Installing the Ravencoin app on the Ledger Device:**

-  Open the Ledger Live Manager
-  Connect and unlock your device
-  If prompted, allow the manager on your device by pressing the right button
-  Find the Ravencoin app
-  Click the install button
-  An Installation window will appear and your device will display processing
-  Close the app installation confirmed window

**Electrum Client Setup**

In order to use your ledger device to manage your Ravencoin you will need to download and install the Electrum-RVN client which can be found here: [https://github.com/traysi/electrum-raven/releases/](https://github.com/traysi/electrum-raven/releases/).  Choose the electrum-rvn-3.2.3-rvn4-setup.exe option.  For more advanced users, the sha256 sum is also included to verify the integrity of the file before installation.  This will work on Windows systems only.

When setting up the Electrum RVN client for the first time follow these steps:

1. You will want to connect your ledger device to your computer, unlock it and enter the Ravencoin app before proceeding.
2. On the first screen, you'll be presented with a text box which has the name of the wallet file that will be created on your computer.  It will have a name default_wallet.  You can either rename this file or leave it as is.
3. Click next
4. On the second screen you'll be presented with three options: Standard wallet, Multi-signature wallet and Import Ravencoin addresses or private keys.  Choose the Standard Wallet option and click next
5. On the third screen you'll see 4 options: Create a new seed, I already have a seed, Use a master key, Use a hardware device.  Select Use a hardware device and click next.
6. The program will scan to see if a hardware device is available.  If so, you should see the option to select an unnamed ledger [ledger, initialized].  Click next.
7. You will be asked to choose the type of addresses in your wallet, there is only one option so you can leave that alone.  In the text box below, it will show the suggested derivation path.  If you don't know what this is don't do anything and click next.
8. The next screen will ask if you want to encrypt the wallet file.  This file contains metadata and a master public key to watch the address you manage using the application.  Private keys are never shared with the application or computer and **remain on the device.**  If you do encrypt the wallet file, you will need to have the device connected and the Ravencoin app open to use the wallet.  If you don't encrypt the wallet you'll be able to open it without the device but you won't be able to send coins or verify the receiving address.
9. The wallet is now set up.

When using the wallet after initial setup:

-  Connect your ledger device and open the Ravencoin app
-  In the electrum raven client select the wallet file you want to open and click next
-  If you encrypted your wallet file, you&#39;ll need to confirm that your device is connected and detected by the wallet software, click next.
-  The wallet will open, and you can send and receive as normal

**Using the Electrum-RVN client**

When the wallet opens, you will see 5 options across the top: File, Wallet, View, Tools and Help.  You will also see 3 tabs labeled History, Send and Receive.  When the wallet is open, your account balance will be shown in the bottom left hand corner of the wallet application.  This will be visible no matter what tab you have open.  The History tab will show the history of transactions using your accounts, the send tab will allow you to broadcast transactions to the Ravencoin blockchain and the receive address will allow you to choose and verify a receiving address for incoming coins.

**Using the Electrum-RVN**  **client to Receive Ravencoin**

- Click the Receive tab
- The wallet will choose a receive address automatically which will be displayed in a text box labeled receiving address. You can use a previously used address if you would like but this doesn't offer optimal privacy.
- To verify the receiving address on your device, click the eye icon on the right-hand side of the Receiving address text box.
- A little text box with the words &quot;showing address&quot; will appear
- Verify the receiving address on your ledger device.  The address will scroll to show the full address and will allow you to confirm by pressing the right button or deny by pressing the left button.

**Using the Electrum-RVN client to send Ravencoin**

- Click the Send Tab
- Paste the target address into the &quot;Pay to&quot; Text box
- You can leave an optional description
- Put the amount of RVN you want to send into the &quot;Amount&quot; text box
- Click the Preview button to preview the transaction before sending it to the ledger device.
- Click the Send button
- A small text box will appear telling you the amount to be sent and the mining fee for the transaction.
- Click yes to proceed
- ** Verify the transaction details on your device**, you'll have to wait a couple of seconds for it to appear.
- It will show the inputs for the transaction with the amounts and the address that will be receiving the transaction.  Click the right button to confirm and the left button to deny.
- If there are multiple inputs and outputs, you'll have to confirm them each individually.
- The transaction will be sent.

**Support**

If you need any help using your ledger device with Ravencoin, you can contact the community through telegram and Discord specifically the ledger-electrum channel.

**Comment by jeroz1** [comment]
@blondfrogs could you create a page that can be referenced with this ledger tutorial?

**Comment by BusterTheFerret** [comment]
Hi,


Thank you very much for doing this... But, this is not very clear for me what you want us to do. I've installed the file and setup the wallet, and then you write:

You will want to connect your ledger device to your computer, unlock it and enter the Ravencoin app before proceeding.

Exactly!! But this IS the problem, right? The Ravencoin App... It doesn't exist, thats why we are at this page in the first place ;)

Please set me straight, because I know you found a way ;)

**Comment by jeroz1** [comment]
Hi!

It’s not merged into the website yet because it does not work yet.

This PR is part of a work in progress to get ledger live support. Which is progressing very slowly unfortunately 

-J

**Comment by BusterTheFerret** [comment]
Hi,


Well, thats one way of doing it... Why not just ask ledger why a project
like this is left to their own, when most others aren't?? I wrote Ledger
and asked directly. I'm looking forward to their explanation ;)



Med venlig hilsen
Dan Hansen

Tågerupvej 1, Druestrup
4682 Tureby
T: +45 5143 6229
E: mail.danhansen@gmail.com
______________________________


Den tor. 3. okt. 2019 kl. 07.51 skrev jeroz1 <notifications@github.com>:

**Comment by Shanker1970** [comment]
Electrum wallet not detect ledger device. My RVN is struck.
Ledger nano s is working well. Other assets are safe.
Pleaze help

**Comment by Konstantins72** [comment]
Yes! You can get access, but you can't send coins! Chaintek wallet Can't see Ledger device

**Comment by jeroz1** [comment]
I forwarded this discussion to the dev who's working on this.

**Comment by BusterTheFerret** [comment]
> Electrum wallet not detect ledger device. My RVN is struck.
> Ledger nano s is working well. Other assets are safe.
> Pleaze help

Maybe this could help you:
https://github.com/standard-error/electrum-raven/issues/22
