### ISSUE TITLE
Dove Wallet list Ravencoin

### ISSUE THREAD

**Issue by 007JAC** [RavenProject/ravenproject.github.io#68]
Hi, 

Dove Wallet is the easiest service to deposit, transfer, trade Ravencoin. We hope anyone can enjoy their financial life anywhere, anytime.

This is our service. 

**Dove Wallet
https://dovewallet.com/**

![Dove_Wallet_official_logo](https://user-images.githubusercontent.com/36462701/61038112-f409b700-a3bb-11e9-9ad3-19fd31cba7fc.png)

**Comment by jeroz1** [comment]
fixed

**Comment by 007JAC** [comment]
Thank you all,
Now only Ravenwiki is left. 
We'd be on the list.
