### ISSUE TITLE
Add BXB Exchange

### ISSUE THREAD

**Issue by RealBokito** [RavenProject/ravenproject.github.io#73]
Add BXB Exchange to the exchange list.
BXB will also donate a percentage of the trading fees back to the Ravencoin community. For this, the following referral link has been created (verified myself, so no issues!).
https://trade.bxb.io/register/html/index.html?code=72T8U8
I have created the logo for the site:
![bxb](https://user-images.githubusercontent.com/42062587/62847528-05a1ef80-bcd7-11e9-8679-34e7617e5285.png)
.

**Comment by jeroz1** [comment]
I found a better logo on their website (https://trade.bxb.io/register/images/newAPP/NEWlogo/mipmap-xhdpi/NEWLOGO.png). Is the code in the link necessary? It looks like a referral. There is no direct link to the RVN trade pair for non-registered users to see?
